[package]
name = "boringdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
thiserror = "1.0.24"
parking_lot = "0.12.1"

[dev-dependencies]
tempfile = "3.6.0"